import { useEffect, useState } from "react";
const db = supabase as any;
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarDays, CheckCircle2, Clock3, FileUp, GraduationCap, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { useSession } from "@/lib/auth";
import { supabase } from "@/integrations/supabase/client";

export const Route=createFileRoute("/dashboard")({component:StudentDashboard});

function StudentDashboard(){
 const navigate=useNavigate();const qc=useQueryClient();const {user,loading}=useSession();const [uploading,setUploading]=useState<string|null>(null);
 useEffect(()=>{if(!loading&&!user)void navigate({to:"/login",search:{redirect:"/dashboard"}})},[loading,user,navigate]);
 const enrollments=useQuery({queryKey:["student-enrollments",user?.id],enabled:!!user,queryFn:async()=>{const {data,error}=await db.from("enrollments").select("id,series_id,starts_at,expires_at,status,test_series(id,title,course,subject)").eq("student_id",user!.id).order("created_at",{ascending:false});if(error)throw error;return data??[]}});
 const sheets=useQuery({queryKey:["student-sheets",user?.id],enabled:!!user,queryFn:async()=>{const {data,error}=await db.from("answer_sheet_submissions").select("id,test_id,marks,feedback,status,submitted_at,checked_at,checked_copy_path,tests(title,series_id)").eq("student_id",user!.id).order("submitted_at",{ascending:false});if(error)throw error;return data??[]}});
 const bookings=useQuery({queryKey:["student-mentorship",user?.id],enabled:!!user,queryFn:async()=>{const {data,error}=await db.from("mentorship_bookings").select("id,status,meeting_url,notes,created_at,mentorship_slots(starts_at,ends_at,mentor_name)").eq("student_id",user!.id).order("created_at",{ascending:false});if(error)throw error;return data??[]}});
 const tests=useQuery({queryKey:["student-tests",enrollments.data?.map((e:any)=>e.series_id).join(",")],enabled:!!enrollments.data?.length,queryFn:async()=>{const ids=enrollments.data!.map((e:any)=>e.series_id);const {data,error}=await db.from("tests").select("id,title,chapter,duration_minutes,marks,series_id,release_at,is_free_sample,status").in("series_id",ids).eq("status","published").order("release_at",{ascending:false});if(error)throw error;return data??[]}});
 const submitSheet=async(test:any)=>{const fileInput=document.createElement("input");fileInput.type="file";fileInput.accept="application/pdf,image/*";fileInput.onchange=async()=>{const file=fileInput.files?.[0];if(!file||!user)return;if(file.size>10*1024*1024){toast.error("Answer sheet must be 10 MB or smaller.");return;}setUploading(test.id);try{const path=user.id+"/"+test.id+"/"+Date.now()+"-"+file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const {error:up}=await supabase.storage.from("answer-sheets").upload(path,file,{upsert:false});if(up)throw up;const enrollment=enrollments.data?.find((e:any)=>e.series_id===test.series_id);const {error}=await db.from("answer_sheet_submissions").insert({student_id:user.id,test_id:test.id,enrollment_id:enrollment?.id??null,answer_sheet_path:path,status:"Pending"});if(error)throw error;await qc.invalidateQueries({queryKey:["student-sheets",user.id]});toast.success("Answer sheet submitted.");}catch(err){toast.error(err instanceof Error?err.message:"Could not upload answer sheet.");}finally{setUploading(null)}};fileInput.click();};
 if(loading||!user)return <div className="page-container py-12"><Skeleton className="h-12 w-64"/><Skeleton className="mt-6 h-40 w-full"/></div>;
 return <main className="min-h-screen bg-[#f8f6f0] py-8 sm:py-12"><div className="page-container space-y-7">
  <section className="rounded-3xl bg-slate-950 p-6 text-white sm:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.18em] text-amber-300">Student dashboard</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Your Revivor preparation hub.</h1><p className="mt-2 text-sm text-slate-300">{user.email}</p></div><ShieldCheck className="size-7 text-amber-300"/></div></section>
  <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-3xl border bg-white p-5"><div className="flex items-center gap-2"><GraduationCap className="size-5 text-amber-600"/><h2 className="font-black">My Test Series</h2></div><div className="mt-5 space-y-3">{enrollments.isLoading?<Skeleton className="h-20"/>:enrollments.data?.length?enrollments.data.map((e:any)=><div key={e.id} className="rounded-2xl border p-4"><div className="flex justify-between gap-3"><div><p className="font-bold">{e.test_series?.title||"Test Series"}</p><p className="text-xs text-slate-500">{e.test_series?.course}{e.test_series?.subject?" · "+e.test_series.subject:""}</p></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">{e.status}</span></div><p className="mt-3 text-xs text-slate-500">Expires {e.expires_at?new Date(e.expires_at).toLocaleDateString():"Not set"}</p></div>):<p className="text-sm text-slate-500">No active test series yet.</p>}</div></div>
  <div className="rounded-3xl border bg-white p-5"><div className="flex items-center gap-2"><Clock3 className="size-5 text-amber-600"/><h2 className="font-black">Available Tests</h2></div><div className="mt-5 space-y-3">{tests.isLoading?<Skeleton className="h-20"/>:tests.data?.length?tests.data.slice(0,8).map((t:any)=><div key={t.id} className="flex items-center justify-between gap-3 rounded-2xl border p-4"><div><p className="font-bold">{t.title}</p><p className="text-xs text-slate-500">{t.chapter||"Full syllabus"} · {t.marks??"—"} marks</p></div><Button size="sm" variant="outline" onClick={()=>void submitSheet(t)} disabled={uploading===t.id}>{uploading===t.id?<span>Uploading…</span>:<><FileUp className="mr-1 size-4"/>Upload sheet</>}</Button></div>):<p className="text-sm text-slate-500">No tests are available for your enrollments yet.</p>}</div></div></section>
  <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-3xl border bg-white p-5"><div className="flex items-center gap-2"><CheckCircle2 className="size-5 text-emerald-600"/><h2 className="font-black">Checked Sheets & Marks</h2></div><div className="mt-5 space-y-3">{sheets.data?.length?sheets.data.map((s:any)=><div key={s.id} className="rounded-2xl border p-4"><div className="flex justify-between gap-3"><p className="font-bold">{s.tests?.title||"Test"}</p><span className="text-sm font-black">{s.marks??"Pending"}</span></div><p className="mt-1 text-xs text-slate-500">{s.status}</p>{s.feedback&&<p className="mt-2 text-sm text-slate-600">{s.feedback}</p>}</div>):<p className="text-sm text-slate-500">No answer sheets submitted yet.</p>}</div></div>
  <div className="rounded-3xl border bg-white p-5"><div className="flex items-center gap-2"><CalendarDays className="size-5 text-amber-600"/><h2 className="font-black">Mentorship Sessions</h2></div><div className="mt-5 space-y-3">{bookings.data?.length?bookings.data.map((b:any)=><div key={b.id} className="rounded-2xl border p-4"><div className="flex justify-between"><p className="font-bold">{b.mentorship_slots?.mentor_name||"Mentorship session"}</p><span className="text-xs font-bold">{b.status}</span></div><p className="mt-1 text-xs text-slate-500">{b.mentorship_slots?.starts_at?new Date(b.mentorship_slots.starts_at).toLocaleString():"Time not set"}</p>{b.meeting_url&&<a className="mt-2 inline-block text-sm font-bold text-amber-700 underline" href={b.meeting_url} target="_blank" rel="noreferrer">Join session</a>}</div>):<p className="text-sm text-slate-500">No mentorship bookings yet.</p>}</div></div></section>
  <div className="flex flex-wrap gap-2"><Button asChild variant="outline"><Link to="/shop">Browse Test Series</Link></Button><Button asChild variant="outline"><Link to="/library">My Library</Link></Button></div>
 </div></main>;
}
